# Generated by Django 5.1.4 on 2026-08-18 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0003_compteurcommande'),
        ('paiements', '0002_tauxchange'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paiement',
            options={'ordering': ['-date_transaction']},
        ),
        migrations.AddField(
            model_name='paiement',
            name='code_confirmation',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='paiement',
            name='date_expiration_code',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='date_remboursement',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='donnees_brutes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='paiement',
            name='justificatif',
            field=models.ImageField(blank=True, null=True, upload_to='paiements/justificatifs/'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='max_tentatives',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='paiement',
            name='montant_frais',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='paiement',
            name='montant_net',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='paiement',
            name='montant_rembourse',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='paiement',
            name='motif_remboursement',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='paiement',
            name='nombre_tentatives',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paiement',
            name='taux_commission',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='commandes.commande'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('reussi', 'Réussi'), ('echoue', 'Échoué'), ('rembourse', 'Remboursé')], default='en_attente', max_length=20),
        ),
    ]
