# Generated by Django 5.1.4 on 2026-07-24 06:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom_boutique', models.CharField(max_length=150)),
                ('sous_domaine', models.SlugField(max_length=60, unique=True)),
                ('theme', models.CharField(default='default', max_length=50)),
                ('devise', models.CharField(default='MGA', max_length=10)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('suspendu', 'Suspendu'), ('en_essai', "En période d'essai")], default='en_essai', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('commercant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='boutique', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Boutique (tenant)',
                'verbose_name_plural': 'Boutiques (tenants)',
            },
        ),
    ]
