# Generated by Django 5.1.4 on 2026-08-07 07:52

import apps.tenants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='theme',
        ),
        migrations.AddField(
            model_name='tenant',
            name='adresse',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tenant',
            name='banniere',
            field=models.ImageField(blank=True, null=True, upload_to='boutiques/bannieres/'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='couleur_primaire',
            field=models.CharField(default='#12181B', max_length=7),
        ),
        migrations.AddField(
            model_name='tenant',
            name='couleur_secondaire',
            field=models.CharField(default='#0E7C66', max_length=7),
        ),
        migrations.AddField(
            model_name='tenant',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='date_suppression',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='date_verification',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='est_supprime',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenant',
            name='est_verifie',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenant',
            name='etape_onboarding',
            field=models.CharField(choices=[('infos_boutique', 'Informations de la boutique'), ('branding', 'Personnalisation visuelle'), ('paiement', 'Configuration des paiements'), ('termine', 'Terminé')], default='infos_boutique', max_length=20),
        ),
        migrations.AddField(
            model_name='tenant',
            name='horaires_ouverture',
            field=models.JSONField(blank=True, default=apps.tenants.models.horaires_par_defaut),
        ),
        migrations.AddField(
            model_name='tenant',
            name='langue_preferee',
            field=models.CharField(choices=[('fr', 'Français'), ('mg', 'Malagasy')], default='fr', max_length=5),
        ),
        migrations.AddField(
            model_name='tenant',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='boutiques/logos/'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='moyens_paiement_actifs',
            field=models.JSONField(blank=True, default=apps.tenants.models.moyens_paiement_par_defaut),
        ),
        migrations.AddField(
            model_name='tenant',
            name='nombre_avis',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tenant',
            name='nombre_ventes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tenant',
            name='note_moyenne',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='tenant',
            name='numero_nif',
            field=models.CharField(blank=True, max_length=30, verbose_name='Numéro NIF'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='numero_stat',
            field=models.CharField(blank=True, max_length=30, verbose_name='Numéro STAT'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='reseaux_sociaux',
            field=models.JSONField(blank=True, default=apps.tenants.models.reseaux_sociaux_par_defaut),
        ),
        migrations.AddField(
            model_name='tenant',
            name='slogan',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='tenant',
            name='telephone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='tenant',
            name='ville',
            field=models.CharField(blank=True, choices=[('antananarivo', 'Antananarivo'), ('toamasina', 'Toamasina'), ('antsirabe', 'Antsirabe'), ('fianarantsoa', 'Fianarantsoa'), ('mahajanga', 'Mahajanga'), ('toliara', 'Toliara'), ('antsiranana', 'Antsiranana'), ('nosy_be', 'Nosy Be'), ('autre', 'Autre')], max_length=30),
        ),
        migrations.AddField(
            model_name='tenant',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
