# Generated by Django 5.1.4 on 2026-08-04 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('code', models.CharField(max_length=6)),
                ('role', models.CharField(choices=[('client', 'Client'), ('commercant', 'Commerçant'), ('superadmin', 'Super administrateur')], max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('est_verifie', models.BooleanField(default=False)),
            ],
        ),
    ]
