# Generated by Django 5.1.4 on 2026-08-07 08:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
        ('tenants', '0002_remove_tenant_theme_tenant_adresse_tenant_banniere_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produit',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Produit', 'verbose_name_plural': 'Produits'},
        ),
        migrations.RenameField(
            model_name='produit',
            old_name='actif',
            new_name='gestion_stock',
        ),
        migrations.AddField(
            model_name='produit',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='date_publication',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='date_suppression',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='est_mis_en_avant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='produit',
            name='est_supprime',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='produit',
            name='marque',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='produit',
            name='meta_description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='produit',
            name='nombre_avis',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produit',
            name='nombre_ventes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produit',
            name='note_moyenne',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='produit',
            name='poids',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='En kg', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='prix_achat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='prix_promo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='promo_debut',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='promo_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='seuil_alerte_stock',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='produit',
            name='sku',
            field=models.CharField(blank=True, max_length=50, verbose_name='Référence (SKU)'),
        ),
        migrations.AddField(
            model_name='produit',
            name='slug',
            field=models.SlugField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='produit',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('publie', 'Publié'), ('archive', 'Archivé')], default='brouillon', max_length=20),
        ),
        migrations.AddField(
            model_name='produit',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='varianteproduit',
            name='prix_supplement',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Montant ajouté au prix de base pour cette variante', max_digits=10),
        ),
        migrations.AddField(
            model_name='varianteproduit',
            name='sku',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sous_categories', to='catalogue.categorie')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['ordre', 'nom'],
                'unique_together': {('tenant', 'slug')},
            },
        ),
        migrations.AddField(
            model_name='produit',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits', to='catalogue.categorie'),
        ),
        migrations.CreateModel(
            name='ImageProduit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='produits/galerie/')),
                ('est_principale', models.BooleanField(default=False)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalogue.produit')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.RemoveField(
            model_name='produit',
            name='photo',
        ),
        migrations.AlterUniqueTogether(
                    name='produit',
                    unique_together={('tenant', 'slug')},
                ),
    ]
