# Generated by Django 5.1.4 on 2026-08-15 08:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commande',
            options={'ordering': ['-date_commande']},
        ),
        migrations.AddField(
            model_name='commande',
            name='adresse_complete',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='annulee_le',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='instructions_livraison',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='mode_livraison',
            field=models.CharField(choices=[('domicile', 'Livraison à domicile'), ('retrait', 'Retrait en boutique')], default='domicile', max_length=20),
        ),
        migrations.AddField(
            model_name='commande',
            name='montant_remise',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='commande',
            name='montant_sous_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='commande',
            name='motif_annulation',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='commande',
            name='nom_destinataire',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='commande',
            name='note_client',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='note_interne',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='numero_commande',
            field=models.CharField(default='TEMP', editable=False, max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commande',
            name='telephone_destinataire',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='lignecommande',
            name='nom_produit',
            field=models.CharField(default='TEMP', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lignecommande',
            name='variante_label',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='HistoriqueStatutCommande',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirmee', 'Confirmée'), ('payee', 'Payée'), ('expediee', 'Expédiée'), ('livree', 'Livrée'), ('annulee', 'Annulée')], max_length=20)),
                ('statut_precedent', models.CharField(blank=True, choices=[('en_attente', 'En attente'), ('confirmee', 'Confirmée'), ('payee', 'Payée'), ('expediee', 'Expédiée'), ('livree', 'Livrée'), ('annulee', 'Annulée')], max_length=20)),
                ('commentaire', models.CharField(blank=True, max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='commandes.commande')),
            ],
            options={
                'verbose_name': 'Historique de statut',
                'verbose_name_plural': 'Historiques de statut',
                'ordering': ['date'],
            },
        ),
    ]
