# Generated by Django 5.1.4 on 2026-08-17 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0002_alter_commande_options_commande_adresse_complete_and_more'),
        ('tenants', '0002_remove_tenant_theme_tenant_adresse_tenant_banniere_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompteurCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField()),
                ('dernier_numero', models.IntegerField(default=0)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compteurs_commande', to='tenants.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'annee')},
            },
        ),
    ]
